all: father son1 son2 son3
father:
	gcc father.c -o father -pthread
son1:
	gcc son1.c -o son1 -pthread
son2:
	gcc son2.c -o son2 -pthread
son3:
	gcc son3.c -o son3 -pthread
clean:
	rm father son1 son2 son3
